### PR TITLE
Add support for art mode

### PR DESCRIPTION
**Pull request by mjg59**
Art mode is controlled via a separate set of APIs on a different websocket channel. This PR adds support and documentation for it.

### CODE REVIEW

**Comment by mjg59** [comment]
Updated to include uploading and deleting photos.

**Comment by xchwarze** [comment]
Thanks for the contribution!

**Comment by brianegge** [comment]
I'm very keen to get this merged and then to pick it up in home assistant.

**Comment by xchwarze** [comment]
I still couldn't run this code against a real TV 
If someone does the QA of it, I could merge it without testing it myself

**Comment by brianegge** [comment]
OK, I just got the frame TV. I can run the code, though I think it needs to be rebased, and I'm not sure what's going on with the license information. I can try changing the art. My main use case is to turn the TV on in art mode. I'll try to get this PR through QA.

**Comment by xchwarze** [comment]
If you test the code of this branch I can merge it and if you have to make changes you can make them in another PR starting from the new state of master

**Comment by mjg59** [comment]
Oh! I have no idea where the license change came from - I can't find that change in my tree.

**Comment by brianegge** [comment]
I was able to start the component and connect the samsung api, but the art mode won't create the websocket.
```
>>> tv.art().set_artmode(True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/brianaegge/dev/samsung-tv-ws-api/samsungtvws/art.py", line 219, in set_artmode
    self._send_art_request({
  File "/Users/brianaegge/dev/samsung-tv-ws-api/samsungtvws/art.py", line 50, in _send_art_request
    self._art_ws_send({
  File "/Users/brianaegge/dev/samsung-tv-ws-api/samsungtvws/art.py", line 42, in _art_ws_send
    self.art_connection = self.open('com.samsung.art-app')
AttributeError: 'SamsungTVArt' object has no attribute 'open'
```
I can call `open('com.samsung.art-app')` but the `SamsungTVArt` doesn't have an open method. Maybe this call is intended to subclass `SamsungTVWS`? Either that or we need to pass in a TV object to  SamsungTVArt.

Here's some logs from my REPL:
```
tv = SamsungTVWS(host='samsung-frame', port=8002, token_file=token_file)
tv.app_list()
{'data': {'attributes': {'name': 'SG9tZUFzc2lzdGFudA==', 'token': '11948268'}, 'connectTime': 1636422372111, 'deviceName': 'SG9tZUFzc2lzdGFudA==', 'id': 'a1aabb61-aeec-4084-826-xxxxx', 'isHost': False}, 'event': 'ms.channel.clientDisconnect'}
info = tv.art().supported()
/Users/brianaegge/dev/samsung-tv-ws-api/lib/python3.9/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'samsung-frame'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
>>> logging.info(info)
INFO:root:True
>>> tv.open('com.samsung.art-app')
<websocket._core.WebSocket object at 0x103d44ac0>
```
```

**Comment by brianegge** [comment]
@mjg59 , what are your thoughts for calling the `SamsungTVWS` class? Seems it should be made a member of the art class. I'm happy to give it a go, but looking to do the least amount of changes to get this merged in.

**Comment by VoiceOfSoftware** [comment]
@brianegge I am seeing exactly the same error AttributeError: 'SamsungTVArt' object has no attribute 'open' when attempting to control a 2021 The Frame from MacOS.

**Comment by xchwarze** [comment]
merged in #27

**Pull request closed without merging**
