### PR TITLE
Enable sequences and add hold_key support

### PR DESCRIPTION
**Pull request by epenet**
This will enable POWER_OFF for FrameTV (= hold POWER for 3 seconds)

### CODE REVIEW

**Comment by epenet** [comment]
I struggled with python 3.7 compatibility in the tests, but now this is ready for merge

**Comment by xchwarze** [comment]
thanks <3

**Comment by epenet** [comment]
Would you be able to bump the version please?

**Comment by xchwarze** [comment]
@epenet done!

**Comment by epenet** [comment]
Thanks

**Pull request merged**
