### PR TITLE
Added support for listing/changing art mode mats

### PR DESCRIPTION
**Pull request by dnetguru**
Added support for
-  listing supported art mode mats
- setting mats on existing art
- an example script that changes mats on all existing art

Tested on 2021 Frame TVs

Reference messages from network capture:
```

{"method":"ms.channel.emit","params":{"data":"{"request":"get_matte_list","id":"72cb249b-b44b-4a05-89e5-03cfe0f78ca6"}","to":"host","event":"art_app_request"}}

--------------------

{"data":"{
  "id": "72cb249b-b44b-4a05-89e5-03cfe0f78ca6",
  "event": "matte_list",
  "matte_type_list": "[
  {
    "matte_type": "none"
  },
  {
    "matte_type": "myshelf"
  

--------------------

{"method":"ms.channel.emit","params":{"data":"{"request":"change_matte","content_id":"MY_F0517","matte_id":"none","id":"5292a036-2ab2-4d19-906b-73e4321d75ff"}","to":"host","event":"art_app_request"}}

--------------------

{"data":"{
  "id": "5292a036-2ab2-4d19-906b-73e4321d75ff",
  "event": "matte_changed",
  "matte_id": "none",
  "target_client_id": "326a44d-688-401c-89e1-b2271d27d39f"
}","event":"d2d_service_message","fro

```

### CODE REVIEW

**Comment by dnetguru** [comment]
Fixes #107

**Comment by dnetguru** [comment]
Fixed flake8 errors

**Review by epenet — APPROVED** [review]
Code looks good (untested)
I wonder if it would be possible to implement all this ART functionnality inside the Async connection...

**Comment by twilightgod** [comment]
@dnetguru is it possible to set to My Shelf style? I tried to use myshelf as matte type, but it doesn’t work

**Comment by dnetguru** [comment]
Sorry it's been a while since I took a look at this. I might have some free time this weekend, might take a look.

Does this work for you for other matte types?
Can you share the code and/or network traffic?

**Pull request merged**
